default:
  image: python:3.12
  interruptible: true

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  POETRY_NO_INTERACTION: "1"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

cache:
  key: "${CI_COMMIT_REF_SLUG}-poetry"
  paths:
    - .cache/pip
    - .cache/poetry
    - .venv

stages:
  - test
  - publish

.main_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

.install_poetry:
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry --version

test:
  stage: test
  extends:
    - .main_rules
    - .install_poetry
  script:
    - poetry install --with tests
    - poetry run pytest

publish:testpypi:
  stage: publish
  extends:
    - .main_rules
    - .install_poetry
  needs:
    - test
  script:
    - poetry config repositories.testpypi https://test.pypi.org/legacy/
    - export POETRY_PYPI_TOKEN_TESTPYPI="${TEST_PYPI_TOKEN}"
    - poetry publish --build -r testpypi --skip-existing
